Titulo // Title
Indiolionel/movimientos pull request #1
Opened 2022-03-16 16:32 UTC by Indiolionel

Hice un titulo // I made a title

2022-03-16 16:35 UTC, jipi-dev commented on src/tabla-mov.js
> +function Tabla() {
Porfavor usar nombres de los componentes en inglés.

2022-03-16 16:37 UTC, jipi-dev commented on src/tabla-mov.js
> +function Tabla() {
El nombre del archivo no debe tener guines medios.

debe ser en cammelcase: ejemplo TableMov.js para leer del tema: https://github.com/airbnb/javascript/tree/master/react#naming

2022-03-16 16:37 UTC, Indiolionel commented on src/tabla-mov.js
> +function Tabla() {
ok bro

2022-03-16 16:38 UTC, jipi-dev requested changes
Viene bien, pero la tabla de movimientos aun no muestra el listado de movimientos, solo muestra un título, tal vez el título deba ser otro componente.

2022-03-16 23:55 UTC, jipi-dev commented on src/App.js
>  import './App.css';
Podrias borrar este import temporalmente. Asi estos estilos no te ponen precondiciones y tal vez te sirva para que no se te deforme el diseño

2022-03-16 23:58 UTC, jipi-dev commented on src/App.js
> +        <Table />
Esto no es critico, pero ojo que te sigue quedando dentro del elemento header.
El header es un tag reservado que simboliza que es la información de cabezera de la pagina NO CONFUNDIR CON HEAD pero la idea del header es que tenga el logo el titulo y el menu para navegar.
Pero el resto del contenido debería estar en <main>
Esto no es un error grave, sino más bien de la semántica del lenguaje

el html deberia quedar con esta estructura.

<header>
Titulo del banco y logo
</header>
<main>
      <P>Todo el contenido
</main>
<footer>
<footer>

Si queres leer mas: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure

2022-03-16 23:59 UTC, jipi-dev commented on src/balance.css
> +.precio {
nombre en inglis

2022-03-17 00:01 UTC, jipi-dev commented on src/balance.css
> +    width: 90%;
ojo con esto, vamos a intentar resolverla de otra manera.

En vez de que le pongas width 90% te conviene que tenga width 100% y luego el que contiene este elemento, tenga un padding de 20 pixeles ponele, entonces de esta manera el "padre" es quien le limita el tamaño y no es un numero 90%, ya que 90% no es ihual en todas las resoluciones entonces cambia esa distancia con los bordes, y es un patrón poco recomendado. Mejor es tener siempre paddings y margenes definidos.

Esto es algo que le vas a ir agarrando la mano con el tiempo.
Es muy subjetivo tambien. Me parece mas ordenado de la otra manera. Da para hablarlo en una videllamada para mostrarte un ejemplo

2022-03-17 00:01 UTC, jipi-dev commented on src/balance.css
> +    display: flex;
muy bien usando flex amigo!

2022-03-17 20:52 UTC, jipi-dev commented on src/table.css
> +    #table2 {
No uses Ids como selector.
Se puede, pero como buena práctica usa siempre clases

2022-03-17 20:52 UTC, jipi-dev commented on src/table.css
> +        width: 90%;
prohibido usar 90%, 80% o cualquier porcentaje que no tenga sentido.
Si queres hacer espacios entre los elementos usa paddings y margins q son para eso

2022-03-17 20:53 UTC, jipi-dev commented on src/table.css
> +table tbody tr:nth-child(2n+1)
Esta bien el recurso, pero es mejor siempre usara las clases, podes aplicar este estilo directamente al atributte.
Intentemos usar solo clases como selectores de css

2022-03-17 20:53 UTC, jipi-dev commented on src/table.js
> +          <table>
Aca esta mal, porque dos tablas, la unica tabla es la de abajo.

Esto es un titulo de una sección, podes usar un simple H y listo

2022-03-17 20:54 UTC, jipi-dev commented on src/table.js
> +        <tr className='atributte'>
te falta ponerle color, osea que haya una clase red y green, para que pinte las letras de toda la row

2022-03-19 16:05 UTC, Indiolionel commented on src/balance.css
> +.precio {
Hecho

2022-03-19 16:09 UTC, Indiolionel commented on src/balance.css
> +    width: 90%;
No, no funca como decis

2022-03-19 16:09 UTC, Indiolionel commented on src/balance.css
> +    display: flex;
]Thanks

2022-03-19 16:09 UTC, Indiolionel commented on src/table.css
> +    #table2 {
oka

2022-03-19 16:13 UTC, Indiolionel commented on src/table.css
> +        width: 90%;
no funca tmp...el margin te deja espacios, no te achica  ni agranda..es lo que me quedo.

2022-03-19 16:13 UTC, Indiolionel commented on src/table.css
> +table tbody tr:nth-child(2n+1)
Hecho ayer !

2022-03-19 16:13 UTC, Indiolionel commented on src/table.js
> +          <table>
ahhh

2022-03-19 16:13 UTC, Indiolionel commented on src/table.js
> +        <tr className='atributte'>
Lo hicimos ayer !

2022-03-22 17:22 UTC, merged